/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package some.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings

/**
 * A simple 'hello world' plugin.
 */
class SomePluginPlugin: Plugin<Settings> {
    override fun apply(settings:Settings ) {
        settings.extensions.create("something",SomeExtension::class.java)
    }
}
